#Eac Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

#1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

#By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
Fib = []
Fib.append(1)
Fib.append(2)
a = 0
b = 0
x = 3
ans = 0
MAX =4000000
while True:
    a = Fib[x-3]
    b = Fib[x-2]
    c = a+b
#    if a%2 == 0:
    #    ans += a
    if b%2 == 0:
        ans += b
    if c >= MAX:
        break
    Fib.append(c)
    x += 1

print(Fib)
print(ans)
